- name: Download WordPress
  get_url:
    url=https://wordpress.org/latest.tar.gz
    dest=/tmp/wordpress.tar.gz
    validate_certs=no

- name: Create /srv/app and set root owner of it
  file:
    path: /srv/app/
    owner: root
    group: root
    state: directory

- name: Create STFP user
  user:
    name: ftpuser
    password: '$6$b4a10f83b068a04d887566acb0a2e81e2b87370753ddc1017ad6dbe0285779f5b11ab72fcf423a538caca6e12618ee59bd76611ec193c5b1964aab46977f0cfa'
    createhome: no

- name: Extract WordPress
  unarchive: src=/tmp/wordpress.tar.gz dest=/srv/app/ copy=no
  become: yes

- name: Update virtualhost
  lineinfile:
    path: /etc/apache2/sites-enabled/000-default.conf
    regexp: '(.)+DocumentRoot /var/www/html'
    line: 'DocumentRoot /srv/app/wordpress'

- name: Update apacheconf
  lineinfile:
    path: /etc/apache2/apache2.conf
    regexp: '<Directory /var/www/>'
    line: '<Directory /srv/app/>'
  notify:
    - restart apache2

- name: Set ftpuser owner of wordpress directory
  file:
    path: /srv/app/wordpress
    recurse: yes
    owner: ftpuser
    group: www-data
    state: directory

- name: Restrict SFTP directories
  blockinfile:
    dest: /etc/ssh/sshd_config
    block: |
      Match User ftpuser
      ChrootDirectory /srv/app/
      ForceCommand internal-sftp -u 0022
      X11Forwarding no
      AllowTcpForwarding no
      PasswordAuthentication yes
  notify:
    - restart sshd

- name: Copy sample config file
  command: mv /srv/app/wordpress/wp-config-sample.php /srv/app/wordpress/wp-config.php creates=/srv/app/wordpress/wp-config.php

- name: Update WordPress config file
  lineinfile:
    dest=/srv/app/wordpress/wp-config.php
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
  with_items:
    - {'regexp': "define\\( 'DB_NAME', '(.)+' \\);", 'line': "define( 'DB_NAME', '{{mysql_db}}' );"}
    - {'regexp': "define\\( 'DB_USER', '(.)+' \\);", 'line': "define( 'DB_USER', '{{mysql_user}}' );"}
    - {'regexp': "define\\( 'DB_PASSWORD', '(.)+' \\);", 'line': "define( 'DB_PASSWORD', '{{mysql_password}}' );"}
    - {'regexp': "define\\( 'DB_HOST', '(.)+' \\);", 'line': "define( 'DB_HOST', '{{mysql_host}}' );"}
